sudo: required
services:
  - docker

before_install:
  - docker build -t nickrockstar/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run nickrockstar/react-test npm run test -- --watchAll=false

after_success:
  - docker build -t nickrockstar/complex-multi-client ./client
  - docker build -t nickrockstar/complex-multi-nginx ./nginx
  - docker build -t nickrockstar/complex-multi-api ./api
  - docker build -t nickrockstar/complex-multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push nickrockstar/complex-multi-client
  - docker push nickrockstar/complex-multi-nginx
  - docker push nickrockstar/complex-multi-api
  - docker push nickrockstar/complex-multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-central-1'
  app: 'complex-multi-docker'
  env: 'ComplexMultiDocker-env'
  bucket_name: 'elasticbeanstalk-eu-central-1-991607386664'
  bucket_path: 'complex-multi-docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
